#
# Copyright (c) 2021 Giorgio Antonioli
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Do NOT use the [versions] tag because it's not supported by ReleasesHub.

[libraries]
android-gp-api = "com.android.tools.build:gradle-api:7.0.4"
android-gp-impl = "com.android.tools.build:gradle:7.0.4"
androidx-appCompat = "androidx.appcompat:appcompat:1.4.1"
androidx-fragment-core = "androidx.fragment:fragment:1.4.1"
androidx-fragment-testing = "androidx.fragment:fragment-testing:1.4.1"
androidx-junit = "androidx.test.ext:junit:1.1.3"
coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
coroutines-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.6.4"
dokka-gp = "org.jetbrains.dokka:dokka-gradle-plugin:1.7.20"
gitHubRelease-gp = "com.github.breadmoirai:github-release:2.4.1"
gradleMavenPublish-gp = "com.vanniktech:gradle-maven-publish-plugin:0.18.0"
junit = "junit:junit:4.13.2"
kotlin-gp = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.20"
kotlin-reflect = "org.jetbrains.kotlin:kotlin-reflect:1.7.20"
kpermissions-buildTools = { module = "com.fondesa.kpermissions.buildtools:build-tools" }
ktlint-gp = "org.jlleitschuh.gradle:ktlint-gradle:11.0.0"
leakCanary = "com.squareup.leakcanary:leakcanary-android:2.9.1"
releasesHub-gp = "com.dipien:releases-hub-gradle-plugin:4.0.0"
robolectric = "org.robolectric:robolectric:4.9"
rxJava2 = "io.reactivex.rxjava2:rxjava:2.2.21"
rxJava3 = "io.reactivex.rxjava3:rxjava:3.0.13"
